name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  step-1:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo Step 1
        
  call-reusableworkflow-DEV:
    uses: ./.github/workflows/ReusableRegression.yml
    with:
      environment: Develop

  step-2:
    runs-on: ubuntu-latest
    steps:
      - name: step 2
        run: echo Step 2

  call-reusableworkflow-QA:
    uses: ./.github/workflows/ReusableRegression.yml
    with:
      environment: Qa
