# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Manual Regression

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Available Environments
        options: 
        - Develop
        - Qa

jobs:
  call-reusableworkflow-QA:
    uses: ./.github/workflows/ReusableRegression.yml
    with:
      environment: ${{ github.event.inputs.environment }}
