# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Reusable Regression

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Available Environments
        options: 
        - Develop
        - Qa
      tags:
        description: 'Trigger reason tags'

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d_%H%M%S')"

    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        cd QAAutomation
        npm install newman
        npm install newman-reporter-allure
        npm install newman-reporter-json-summary

    - name: Running Regression-APIs
      run: |
        cd QAAutomation
        mkdir newman        
        node "./newman-run.js" "./Cats-Breeds.postman_collection.json" "./workspace.postman_globals.json" "./${{ inputs.environment }}.postman_environment.json"
        node "./newman-run.js" "./Cats-Facts.postman_collection.json" "./workspace.postman_globals.json" "./${{ inputs.environment }}.postman_environment.json" false

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Generate allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      #id: allure-report
      with:
        allure_results: QAAutomation/allure-results
        #gh_pages: gh-pages
        allure_report: QAAutomation/allure-report
        allure_history: QAAutomation/allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: QAAutomation/allure-history

    - uses: actions/upload-artifact@v2
      name: Generate Artifacts
      with:
        name: Cats-artifact-${{ steps.date.outputs.date }}
        path: |
          ${{ github.workspace }}/QAAutomation/newman/
          ${{ github.workspace }}/QAAutomation/allure-report/
          ${{ github.workspace }}/QAAutomation/allure-results/
          ${{ github.workspace }}/QAAutomation/allure-history/
          ${{ github.workspace }}/QAAutomation/Cats-*/
          
    - name: Analyze consolidated results
      id: consolidatedResult
      uses: notiz-dev/github-action-json-property@release
      with: 
        path: 'QAAutomation/newman/Result.json'
        prop_path: 'Run.Failures'

    - name: Automated result
      if: ${{ steps.consolidatedResult.outputs.prop }}
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Regression test failed.')
